application: kisstodo2
version: 5
runtime: python
api_version: 1

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine/appstats/ui.py

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'
  login: admin
  
- url: /static
  static_dir: static
  expiration: '0'
  login: admin
  
- url: /todo/send_mail
  script: djangoappengine/main/main.py
  login: admin  
  
- url: /.*
  script: djangoappengine/main/main.py
  login: admin

builtins:
- datastore_admin: on
- remote_api: on
